backend:
  name: git-gateway
  repo: manikantan07/netlify-1
  branch: main

media_folder: "assets/images"  # Correct relative path
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }