backend:
  name: git-gateway
  branch: main  # Change to your branch name

media_folder: "assets/images/uploads" # Where uploaded images will be stored
public_folder: "/images/uploads"      # Path to access uploaded images

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
